server:
  port: 8083
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300
  jackson:
    default-property-inclusion: non_null #排除为null的属性
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
ribbon:
  ConnectionTimeout: 500
  ReadTimeout: 3000
hystrix:
  command:
    #全局超时时长
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000