#端口
server:
  port: 10010
#服务名称
spring:
  application:
    name: ly-gateway

#配置服务注册地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

zuul:
  prefix: /api #添加路由前缀
  routes:
    item-service: /item/**
hystrix:
  command:
    #全局超时时长
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
ribbon:
  ConnectTimeout: 1000  #连接超时时间(ms)
  ReadTimeout: 3500 #通信超时时间(ms)
  MaxAutoRetries: 0 #同一实例的重试次数
  MaxAutoRetriesNextServer: 0 #同一服务不同实例重试次数