server:
  port: 8084
spring:
  application:
    name: page-service
  thymeleaf:
    cache: false #关闭thymeleaf cache
  rabbitmq:
    host: localhost
    username: leyou
    password: leyou
    virtual-host: /leyou

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
ribbon:
  ConnectionTimeout: 500
  ReadTimeout: 6000
hystrix:
  command:
    #全局超时时长
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000