server:
  port: 8081

spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud_demo
    username: root
    password: root

eureka:
  client:
    service-url:
      #配置eureka注册地址
      defaultZone: http://127.0.0.1:8761/eureka,http://127.0.0.1:8762/eureka